SET DATABASE butterflynet;

DROP TABLE RECORDS;
DROP TABLE PROJECTS;

CREATE TABLE PROJECTS (
    id SERIAL PRIMARY KEY,
    auth_key VARCHAR(255) NOT NULL
);

CREATE TABLE RECORDS (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL,
    timestamp BIGINT NOT NULL,
    content TEXT,
    FOREIGN KEY (project_id) REFERENCES PROJECTS(id)
);

INSERT INTO PROJECTS(auth_key) VALUES ('abcd-1234');